### ISSUE TITLE
Experimental Results

### ISSUE THREAD

**Issue by Leminhbinh0209** [uakarsh/docformerv2#2]
Hi,

Thank you for your great effort!
I wonder whether you finished the code? Or can you share which part of the code is missing now, and needs to be implemented?

Thanks,

**Comment by uakarsh** [comment]
HI @Leminhbinh0209 , thank you for your kind words. I really felt happy that you are interested in my work.

Due to health issues, and my work, I haven't been able to give time to complete the code.

The part which is currently left is:
- Implementing the pre-training task
- Fine-tuning on the tasks, that the authors have proposed.

**Comment by Leminhbinh0209** [comment]
Great thanks, @uakarsh , for sharing the information!
